### ISSUE TITLE
Component Request - BlockStaffList

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/library-website-nuxt#106]
## Component Description

This component is used on the staff listing page as an individual block to display an individual staff member in the list section. 
+ Hover states should be blue underlines like the FooterSock and the links should start and stay var(-color-primary-blue)
+ It can have a photo or just the arrow

## Design

Please also see attached screenshots for quick reference.

-   Desktop: https://www.figma.com/file/BLO5HP8AphPr0KEacFPjs8/COPY-of-UI-Pattern-Library-Client-Facing-Final?node-id=887%3A30225

## Props (item)

```js
props: {
    image: {
        type: Object,
        default: () => {},
    },
   to: { (for name-link)
        type: String,
        default: ""
    },
    staffName: {
        type: String,
        default: ""
    },
    jobTitle: {
        type: String,
        default: ""
    },
    location: {
        type: Array,
        default: () => []
    },
    email: {
        type: String,
        default: ""
    },
    phone: {
        type: String,
        default: ""
    },
    department: {
        type: String,
        default: ""
    },
}
```

## Developer Tips
(CSS is at the end of this section)

+ there is an image or default <svg-heading-arrow>
+ https://www.library.ucla.edu/staff?search_api_views_fulltext=Elizabeth+McAulay
+ Hover states should be blue underlines like the FooterSock
+ It can have a photo or just the arrow
+ Book a consultation - use a page level CONST for this link: LibCal calendar appointment page https://calendar.library.ucla.edu/appointments?_ga=2.172590307.1985418451.1624934053-1078051476.1578938531
or 

you can create a `constants.js` file and
```js
 // constants.js
 export const CONSTANT_1 = 'CONSTANT_1';
 export const CONSTANT_2 = 'CONSTANT_2';
 export const CONSTANT_3 = 'CONSTANT_3';
```
 // And call it like this
 `import { CONSTANT_1 } from 'constants';`

or create a `.envlocal` for the secret files and `.env` for everything else

### Links:
+ **title** - detail page of the staff member NuxtLink
+ **location**  - library department page NuxtLink
+ **email** - mailto
+ **phone** - if mobile makes a call

### You might want to divide it up into image and text divs and use flex.
```html
<template lang="html">
    <div class="block-staff-list">
        <responsive-image
            :image="image"
            :aspect-ratio="100"
            class="image"
        />
        <div class="meta">
        </div>
    </div>
</template>
```

### CSS
```css
.block-staff-list {
    max-width: 959px;
    height: 396px;
    margin-left: 80px;
    border: 2px solid var(--color-primary-lightest-blue);
    border-radius: var(--rounded-slightly-all);
    font-family: Karbon;
    color: var(--color-black);

    .image {
        ratio:

        display: flex;
        flex-direction: row;
        flex-wrap: nowrap;
        justify-content: flex-start;
        align-content: stretch;
        align-items: center;
    }
    .arrow { this is not right but the right color
        border-color:  var(--color-visit-fushia-base);
    }
    .meta {
        .staffName {
          font-size: 48px;
          color: var(--color-primary-blue);
        }

        .jobTitle {
            margin-top: 18px;
            font-size: 18px;
        }

        .department {
            color: var(--color-secondary-black) (change the variable --color-secondary-black) to #434343)
            border-right: 
        }
    }

    @media #{$lte-phone} {
        width: 80%; ???

        display: flex;
        flex-direction: column;
        flex-wrap: nowrap;
        justify-content: center;
        align-content: stretch;
        align-items: center;
    }
}
```

## Child components
+ `<svg-responsive-image/>` similar to the bannerFeature
+ `<svg-heading-arrow />` visit color var(--color-visit-fushia-base) https://github.com/UCLALibrary/library-website-nuxt/blob/main/assets/svg/heading-arrow.svg

### ICONS
+ import the phone icon - name it `icon-phone.svg`
+ import the consultation icon - name it `icon-consultation.svg`
- [x] rename `online-icon.svg` -->`icon-online.svg`
- [x] rename `location-icon.svg` -->`icon-location.svg`

## Screenshots
The task is to build one of these with the ability to have the image or the default arrow.
<img width="610" alt="Screen Shot 2021-06-29 at 11 24 14 AM" src="https://user-images.githubusercontent.com/751697/123848407-8b7bb380-d8cc-11eb-8bd8-a07da0a7620d.png">
