### ISSUE TITLE
Component Request - SectionStaffList

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/library-website-nuxt#107]
## Component Description

This component is used on the staff listing page as an to display the list of staff member. 

## Design

Please also see attached screenshots for quick reference.

-   Desktop: https://www.figma.com/file/BLO5HP8AphPr0KEacFPjs8/COPY-of-UI-Pattern-Library-Client-Facing-Final?node-id=887%3A30225

- Mobile: The blocks should stack vertically

## Slots

Name and description of any slots needed.

## Props

```
props: {
   items: {
        //Array of BlockStaffArticleList objects [{image: image, to: to, category: category, title: title, date: date, authors: authors
    description: description},...]
        type: Array,
        default: () => []
    },
}
```

## Developer Tips

CSS
```css
.section-staff-list {
    max-width: 959px;
    margin-bottom: 24px;

    &:last-child {
        margin-bottom: 0px;
    }
}
```

## Child components
<block-staff-list />

## Screenshots
<img width="389" alt="Screen Shot 2021-06-25 at 3 40 28 PM" src="https://user-images.githubusercontent.com/751697/123861261-d05b1680-d8db-11eb-818d-2abe122a240d.png">
